MATEMATICA

MATRIZES /* FORMA MATEMATICA DE UMA LISTA */
	m = linha
	n = coluna
	Aij = VALORES	
	i = linha
	j = coluna

MATRIZ QUADRADA /* M = N */
	DIAGONAL PRINCIPAL /* I = J */
	DIAGONAL SECUNDARIA /* I + J = 1 + N */
	
MATRIZ DIAGONAL /* TODOS ELEMENTOS FORA DA DIAGONAL = 0 - SUAS DETERMINANTES SAO O PRODUTO DA DIAGONAL PRINCIPAL */
MATRIZ TRIANGULAR SUPERIOR /* VALORES ACIMA DA DIAGONAL = 0 */
MATRIZ TRIANGULAR INFERIOS /* VALORES ABAIXO DA DIAGONAL = 0 */
MATRIZ IDENTIDADE /* DIAGONAL = 1 E O RESTO = 0 */
MATRIZ NULA /* TUDO ZERO = O3 */
MATRIZ OPOSTA /* INVERTE SINAL DOS VALORES */
MATRIZ TRANPOSTA /* TROCA LINHA COM COLUNA - A2x3 -> AT3x2 */

MATRIZ SIMETRICA /* QUADRADA */
				 /* MATRIZ IGUAL A SUA TRANSPOSTA */
				 /* VALORES QUE CERCAM A DIAGONAL SE ESPELHAM - Aij = Aji */

MATRIZ ASSIMETRICA /* QUADRADA */
				   /* TRANSPOSTA DA MATRIZ = OPOSTA */
				   /* VALORES QUE CERCAM A DIAGONAL SE ESPELHAM POREM OPOSTOS */

MATRIZ INVERSA /* A.A-1 = I - MULTIPLICA PELA INVESA (ATRIBUI INCOGNITAS) E IGUALA A IDENTIDADE */
				/* SOMENTE INVERSIVEL SE DETERMINANTE NAO FOR ZERO */
				/* MACETE ORDEM 2 - MULTIPLICA O INVERSO DA DETERMINANTE ORIGINAL PELA MATRIZ ORIGINAL POREM - TROCA A DIAG PRINCIPAL DE LUGAR E INVERTE SINAL DA SECUNDARIA */ 
OPERAÇOES

	IGUALDADE ENTRE MATRIZES /* TUDO IGUAL , ELEMENTOS E ESTRUTURA */
	ADIÇAO E SUBTRAÇAO /* MESMA ESTRUTURA - OPERA VALOR A VALOR */
	MULTIPLICAÇAO POR NUMERO REAL /* 3.A - MULTIPLICA TODOS OS VALORES POR 3 */

	MULTIPLICAÇAO ENTRE MATRIZES /* COLUNA DA 1 DEVE SER = LINHA DA 2 /-/ PRODUTO = LINHA 1 X COLUNA 2 */
	
	PROPRIEDADES DE MULTIPLICAÇAO 	/* NAO HA COMUTATIVIDADE - A.B NAO E IGUAL A B.A */
									/* ASSOCIAÇAO COM NUMERO REAL X - X(A.B) = A(X.B) = B(X.A) */
									/* ASSOCIAÇAO COM MATRIZES A(B.C) = B(A.C) = C(B.A) */
									/* DISTRIBUTIVA (CHUVEIRINHO) - A.B + A.C = A(B+C) */
									/* MATRIZ IDENTIDADE = NEUTRA - NAO ALTERA NADA */
	
DETERMINANTE /* CALCULADA A PARTIR DE MATRIZ QUADRADA - PRODUTO DA DIAGONAL PRINCIPAL - PRODUTO DIAGONAL SECUNDARIA */
			/* CASO ORDEM 3 - REPETE COLUNA 1 E 2 -> REALIZA A SOMA DOS PRODUTOS DAS DIAGONAIS E SUBTRAI */
			/* ORDEM 1 - É´O PROPRIO VALOR */
			
	PROPRIEDADES
		BINET /* detA.detB = det(A.B) */
		TRANSPOSTA /* A DETERMINANTE DAS DUAS SAO IGUAIS - TRANPOSTA E ORIGINAL */
		MULTIPLICAÇAO DE FILA /* SE MULTIPLICAR LINHA OU COLUNA DE UMA MATRIZ, SUA DET SERA MULTIPLICADO PELO MESMO */
		MULTIPLICAÇAO DE MATRIZ POR REAL /* SE MULTIPLICAR TODA A MATRIZZ POR X SUA DET NOVA SERA - detXA = X elevado a coluna.detA */  
		DET ZERO /* DUAS FILAS PARALELAS IGUAIS OU UMA FILA COM OS VALORES ZERO */
		




