MATEMATICA

MATRIZES /* FORMA MATEMATICA DE UMA LISTA */
	m = linha
	n = coluna
	Aij = VALORES	
	i = linha
	j = coluna

MATRIZ QUADRADA /* M = N */
	DIAGONAL PRINCIPAL /* I = J */
	DIAGONAL SECUNDARIA /* I + J = 1 + N */
	
MATRIZ DIAGONAL /* TODOS ELEMENTOS FORA DA DIAGONAL = 0 - SUAS DETERMINANTES SAO O PRODUTO DA DIAGONAL PRINCIPAL */
MATRIZ TRIANGULAR SUPERIOR /* VALORES ACIMA DA DIAGONAL = 0 */
MATRIZ TRIANGULAR INFERIOS /* VALORES ABAIXO DA DIAGONAL = 0 */
MATRIZ IDENTIDADE /* DIAGONAL = 1 E O RESTO = 0 */
MATRIZ NULA /* TUDO ZERO = O3 */
MATRIZ OPOSTA /* INVERTE SINAL DOS VALORES */
MATRIZ TRANPOSTA /* TROCA LINHA COM COLUNA - A2x3 -> AT3x2 */

MATRIZ SIMETRICA /* QUADRADA */
				 /* MATRIZ IGUAL A SUA TRANSPOSTA */
				 /* VALORES QUE CERCAM A DIAGONAL SE ESPELHAM - Aij = Aji */

MATRIZ ASSIMETRICA /* QUADRADA */
				   /* TRANSPOSTA DA MATRIZ = OPOSTA */
				   /* VALORES QUE CERCAM A DIAGONAL SE ESPELHAM POREM OPOSTOS */

MATRIZ INVERSA /* A.A-1 = I - MULTIPLICA PELA INVERSA (ATRIBUI INCOGNITAS) E IGUALA A IDENTIDADE */
				/* SOMENTE INVERSIVEL SE DETERMINANTE NAO FOR ZERO */
				/* MACETE ORDEM 2 - MULTIPLICA O INVERSO DA DETERMINANTE ORIGINAL PELA MATRIZ ORIGINAL POREM - TROCA A DIAG PRINCIPAL DE LUGAR E INVERTE SINAL DA SECUNDARIA */ 
OPERAÇOES

	IGUALDADE ENTRE MATRIZES /* TUDO IGUAL , ELEMENTOS E ESTRUTURA */
	ADIÇAO E SUBTRAÇAO /* MESMA ESTRUTURA - OPERA VALOR A VALOR */
	MULTIPLICAÇAO POR NUMERO REAL /* 3.A - MULTIPLICA TODOS OS VALORES POR 3 */
	
	MULTIPLICAÇAO ENTRE MATRIZES /* COLUNA DA 1 DEVE SER = LINHA DA 2 /-/ PRODUTO = LINHA 1 X COLUNA 2 */
	
	PROPRIEDADES DE MULTIPLICAÇAO 	/* NAO HA COMUTATIVIDADE - A.B NAO E IGUAL A B.A */
									/* ASSOCIAÇAO COM NUMERO REAL X - X(A.B) = A(X.B) = B(X.A) */
									/* ASSOCIAÇAO COM MATRIZES A(B.C) = B(A.C) = C(B.A) */
									/* DISTRIBUTIVA (CHUVEIRINHO) - A.B + A.C = A(B+C) */
									/* MATRIZ IDENTIDADE = NEUTRA - NAO ALTERA NADA */
	
DETERMINANTE /* CALCULADA A PARTIR DE MATRIZ QUADRADA - PRODUTO DA DIAGONAL PRINCIPAL - PRODUTO DIAGONAL SECUNDARIA */
			/* CASO ORDEM 3 - REPETE COLUNA 1 E 2 -> REALIZA A SOMA DOS PRODUTOS DAS DIAGONAIS E SUBTRAI */
			/* ORDEM 1 - É´O PROPRIO VALOR */
			
	PROPRIEDADES
		BINET /* detA.detB = det(A.B) */
		TRANSPOSTA /* A DETERMINANTE DAS DUAS SAO IGUAIS - TRANPOSTA E ORIGINAL */
		MULTIPLICAÇAO DE FILA /* SE MULTIPLICAR LINHA OU COLUNA DE UMA MATRIZ, SUA DET SERA MULTIPLICADO PELO MESMO */
		MULTIPLICAÇAO DE MATRIZ POR REAL /* SE MULTIPLICAR TODA A MATRIZ POR X SUA DET NOVA SERA - detXA = X elevado a coluna.detA */  
		DET ZERO /* DUAS FILAS PARALELAS IGUAIS OU UMA FILA COM OS VALORES ZERO */

PA x PG

PA /* PROGRESSAO ARITMETICA - NUMERO = ANTERIOR + UM NUMERO FIXO  */
	/* RAZAO = NUMERO - ANTERIOR */
	/* RAZAO PODE SER NEGATIVA, RESULTA EM SEQUENCIA DECRESCENTE */
	/* RAZAO = 0 , PA CONSTANTE */
	
	NOTAÇAO /* a1, a2, a3 */

	TERMO GERAL PA -> 𝑎𝑛 = 𝑎1 + (𝑛 − 1) ∙ R /* NAO NECESSARIAMENTE O A1 É O INICIO */
	
	TRES TERMOS P.A /* O CENTRAL É = A MEDIA ARITMETICA DOS 2 TERMOS ENTRE ELE */
		a2 = a1 + a3/2
	
	INTERPOLAÇAO /* RECEBE 2 TERMOS PARA DESCOBRIR A RAZAO */
	SOMA DOS N PRIMEIROS TERMOS - Sn = (a1+an).n/2
	
PG /* PROGRESSAO GEOMETRICA - NUMERO = ANTERIOR . RAZAO FIXA (q)*/
	/* CRESCENTE x DECRESCENTE - DEPENDE DO a1 e da RAZAO(q) */
	
	RAZAO 1 - PG CONSTANTE 
	RAZAO > 1 - /* a1 > 0 = crescente - a1 < 0 = decrescente */ 
	RAZAO ENTRE 1 e 0 -> /* a1 > 0 = decrescente - a1 < 0 = crescente */
	RAZAO < 0 - ALTERNA
	
	TERMO GERAL - 𝑎𝑛 = a1.qEn-1
	TERMO CENTRAL PG -> a2E2 = a1.a3
	SOMA TERMOS FINITA - Sn = a1.(qEn-1)/q-1
	INFINITA - RAZAO ENTRE 1 E -1 - S= a1/1-q 
	PRODUTO N PRIMEIROS TERMOS - Pn = a1En.qE n(n-1)/2

ANALISE COMBINATORIA /* QUANTAS MANEIRA/POSSIBLIDADES DE */

	PRINCIPIO MULTIPLICATIVO /* PROCESSO DIVIDIDO EM ETAPAS, MULTIPLICASE AS POSSIBILIDADES DE CADA ETAPA */
			/* PROCESSO DE ESCOLHA POR ETAPA, UM DE CADA VEZ PODENDO REPETIR OU NAO */
			/* CONECTIVO 'E', ETAPAS OBRIGATORIAS */
		EX : /* VESTIR-SE DE CALÇA E BLUSA, CALÇA =3 e BLUSA =4 -> 4x3 */
	
	PRINCIPIO ADITIVO /* NAO HÁ COMBINAÇAO */
		/* CONECTIVO 'OU' , EXCLUDENTE */
		EX: /* JOAO VESTE 3 SAPATOS OU 3 TENIS -> 3+3 */
	
	PRINCIPIO DA CASA DOS POMBOS /* IMPREVISIBILIDADE - N > M - uma casa tera mais de 1 N */
		/* LOGO PELO MENOS UMA CASA TERA 2 N */
		/* OCUPA ALEATORIAMENTE */
		/* COM NUMERO GRANDE, N/M - SE RESTO = 0 -> QUOCIENTE É O RESULTADO */
			/* SE RESTO DIFERENTE DE 0 -> QUOCIENTE + 1 É O RESULTADO */
	
	FATORIAL /* NUMEROS NATURAIS */
		/* 5! = 5.4.3.2.1 */
	
	PERMUTAÇAO SIMPLES /* NUMERO DE COMBINAÇOES DE TROCAR DE ELEMENTOS ENTRE SI */
		/* SEM ELEMENTOS REPETIDOS */
		/* FATORIAL */
		RECONHECENDO PERMUTAÇAO NO ENUNCIADO
			/* N DE FILAS DIFERENTES */
			/* N DE ORDENS DIFERENTES */
			/* N DE POSSIBILIDADES DE TROCAR OS ELEMENTOS ENTRE SI */
			/* N DE POSSIBILIDADES DE DISTRIBUIR N ELEMENTOS EM N LUGARES */
			
		PERMUTAÇAO RESPEITANDO ORDEM ESPECIFICA /* EX ALFABETICA */
			ELEMENTOS!/ELEMENTOS QUE RESPEITAM ORDEM!
		
		DESARRANJO/PERMUTAÇAO CAOTICA /* ELEMENTOS NAO PODEM ESTAR NA POSIÇAO ORIGINAL */
			Dn = n!. (1/2!-1/3!+1/4!-...+)
			
		COM RESTRIÇOES
			ELEMENTO FIXO /* SUBTRAI O FIXO E FAZ FATORIAL COM OS MOVEIS */
					/* CASO O FIXO SEJA UMA CASA E MAIS DE UM ELEMENTO POSSIVEL, APENAS MULTIPLICA PELA NUMERO DE ELEMENTO */
				/* CASO DE 2 FIXOS E QUE PERMUTEM TAMBEM ENTRE SI - P1! x P2! */
				
			GRUPO DE ELEMENTO JUNTO /* SO CONTA COMO UNIDADE */
				/* CASO PERMUTEM ENTRE ELES, MULTIPLICA AS DUAS PERMUTAÇOES */
	
	PERMUTAÇAO COM REPETIÇAO
		/* APENAS FATORIAL COMUM DIVIDIDO PELO NUMERO DE VEZES QUE UM ELEMENTO REPETE */
		/* SE HOUVER MAIS DE UM ELEMENTO REPETIDO, MULTIPLICA-SE ENTRE ELES */
	
	PERMUTAÇAO CIRCULAR /* ELEMENTOS DISPOSTOS EM UM CIRCULO */
		/* IMPORTA A POSIÇAO EM RELAÇAO AOS OUTRAS, SE MEXE MAS A POSIÇAO SE MANTEM */
		/* PARA CALCULAR EXCLUI O PRIMEIRO (N -1) E FAZ FATORIAL */
		/* BIZUUUU - AO FIXAR UM ELEMENTO, O RESTO SE TORNA PERMUTAÇAO SIMPLES, POR ISSO TIRA O PRIMEIRO */
		EX : 4 MENINOS 4 MENINAS - COMBINAÇAO SENDO QUE SEMPRE 1 MENINO ENTRE 2 MENINAS
			/* PC4 e P4 */
		
		COM RESTRIÇAO FIXA /* SUBTRAI OS FIXOS E FATORIAL NO RESTANTE */
	
	ARRANJO /* PODE HAVER REPETIÇAO ENTRE OS TERMOS (NUMERO MAIOR DE POSSIBILIDADES) OU SEJA A B C difere B C A */
	
		SIMPLES /* BIZU PROVA REAL : POPULAÇAO -> AMOSTRA -> FUNÇOES DIFERENTES */
			/* BIZU : ATIVIDADE EXERCIDA/HORARIO/LOCAL QUE VAO */
			/* FORMULA A(n, k) = n! / (n-k)! */
			
	COMBINAÇAO /* NAO PODE HAVER REPETIÇAO ENTRE TERMOS (MENOR NUMERO DE POSSIBILIDADES) OU SEJA A B C = C B A */
			/* FORMULA C(n, k) = n! / (k! * (n-k)!) */
	
	
FORMULA PARA DECRESCIMO/AUMENTO EXPONENCIAL FIXO
	V(t) = V0 . (1 - r)^t /* vt é o valor final com o tempo, v0 o inicial */

FUNÇAO /* uma coisa varia com relaçao a outra */

	INJETORA /* VALOR DO CONTRADOMINIO (Y) SO PODE EQUIVALER A UM DO DOMINIO (X) */
			
	SOBREJETORA /* TODOS OS VALORES DO CONTRADOMINIO (Y) TEM QUE TER UM CORRESPONDENTE DO DOMINIO (X) */

	BIJETORA /* É OS DOIS */

	!!BIZU /* NO GRAFICO CORTA-SE UMA LINHA PARALELA AO X, SE CORTAR A FUNÇAO 2X NAO E INJETORA */

	FUNÇAO AFIM (1 GRAU) /* f(x) = ax + b */
		/* (a,b) pertence aos reais e a diferente de 0 */
		y /* variavel dependente */ x /* variavel independente */
		GERA UMA P.A COM RAZAO = a /* an = x */
		
		ponto - (x,y) / reta = unidao dos pontos 
			prova real se o ponto esta na reta /* joga os pontos na funçao */
			
		b = 0 /* funçao linear */
			/* funçao diretamente proporcional (se dobrar o x o y dobra) */
			a = 1 /* funçao identidade */ - /* reta bissetriz dos quadrantes impares */
			a = -1 /* reta bissetriz dos quadrantes pares */
		
		a > 0 = crescente /* x aumenta y aumenta */  
		a < 0 = decrescente /* x aumenta y diminui */
		a = 0 - costante
		
		Duas retas paralelas - a1=a2
		Duas retas concorrentes - se cruzam - a1 diferente de a2
			perpendiculares (90) - sera o oposto e inverso da outra
		
		RAIZ /* VALOR DE X QUE ANULA O Y */
		
		interseçoes nos eixos x,y 
			corta o X no y=0 (raiz da funçao)
			corta o Y no b (x=0 - a.0 = 0)
		
	FUNÇAO DO SEGUNDO GRAU (QUADRATICA) /* PARABOLA */
		
		f(x) = ax2 + bx + c 
		a diferente de 0
		
		a > 0 - CONCAVIDADE PRA CIMA
		a < 0 - CONCAVIDADE PRA BAIXO
		
		b = 0 /* vertice sobre o Y */
		b > 0 /* corta o Y crescendo */
		b < 0 /* corta o Y decrescendo */
			
		RAIZES
			DELTA = b^2 - 4ac
				D = 0 DUAS RAIZES IGUAIS
				D > 0 RAIZES REAIS DIFERENTES 
				D < 0 NAO HA RAIZES REAIS
			
			x = -b(+- raiz de delta)/2a
			   
		TERMO INDEPENDENTE (c) /* onde toca o eixo Y */
		
		VALOR MAX/MIN - VERTICE
			Xv = -b/2a OU media entre as raizes 
			Yv = -delta/4a 
		
		FUNÇAO EXPONENCIAL
			
			VARIAVEL X É O EXPOENTE f(x) = b^x !!!!PG DE RAZAO B !!!!
			!! BASE SEMPRE > 0 e DIFERENTE DE 1
			
			BASE > 1 CRESCENTE
		    1 > BASE > 0 DECRESCENTE 
			
			NO GRAFICO, CURVA EXPONENCIAL
			GRAFICO FAZ CURVA ASSINTOTA NA EXPONENCIAL /* NUNCA ENCOSTA NO EIXO X, APENAS SE APROXIMA */
			!!O GRAFICO SEMPRE CORTA O Y NO NUMERO 1 !!
			
			FORMA GERAL
				f(x) = c +- a.b^k.x 
					se + -> menor resultado = c 
					se - -> maior resultado = c 
			   
			EQUAÇOES EXPONENCIAIS
				!!BIZUS - TENTAR IGUALAR BASES ou ATRIBUI VARIAVEL AOS COMUNS !!
			
			INEQUAÇAO EXPONENCIAL
				!!MESMA COISA POREM, SE S BASES FOREM ENTRE 0 e 1, AO IGUALAR OS EXPOENTES, INVERTE !!
				
		FUNÇAO LOGARITMA/LOGARITMOS
			
			
		
			
			
	
		
	
		
	


	




