BANCOS NA ERA DIGITAL

	BANCOS DIGITALIZADOS /* BANCOS TRADICIONAIS OFERECENDO CANAIS DIGITAIS PARA O CLIENTE */
		/* SERVIÇOS (SALDOS, EXTRATOS, FATURA, TRANSFERENCIA ETC */
		/* OBS: EM ALGUM MOMENTO VAI À AGENCIA */
		
		INTERNET BANKING /* VIA NAVEGADOR/BROWSER DE INTERNET */
		MOBILE BANKING /* VIA APP PARA CELULAR */
	
	CORRESPONDENTES BANCARIOS /* CONTRATADOS POR INSTITUIÇAO PARA ATENDER AOS CLIENTES */
		/* EMPRESA PUBLICA PODE ATUAR COMO CORRESPONDENTE */
		
		EX: LOTERICA
		
		OBJETIVOS: REGULADORES (INCLUSAO E DEMOCRATIZAÇAO)
					   AMPLIA A REDE DE ATENDIMENTO DO BANCO
					   PARA O CORRESPONDENTE: ATRAI CLIENTE, GANHA RECEITA
					   PARA O PUBLICO: MAIS LOCAIS DE ATENDIMENTO
			
		SERVIÇOS: PROPOSTA DE ABERTURA DE CONTA /* SO RECEBE A PROPOSTA */
					  MOVIMENTAÇAO DE CONTAS
					  RECEBIMENTOS, TRANFERENCIAS E PAGAMENTOS
					  EXECUÇAO DE ORDEM DE PAGAMENTO
					  PROPOSTAS DE OPERAÇAO DE CREDITO /* SO RECEBE A PROPOSTA */
					  PROPOSTA DE CARTAO DE CREDITO /* SO RECEBE A PROPOSTA */
					  RECEPCIONAR OPERAÇOES DE CAMBIO /* SO RECEBE A PROPOSTA */
					  SERVIÇOS COMPLEMENTARES
			
		EXIGENCIAS: RELAÇAO FORMALIZADA COM OS ATENDENTES (EQUIPE)
						ESPECIFICAR QUE E PRESTADOR DE SERVIÇO
						PADROES DE TARIFAS PADRONIZADO PELO BANCO
						VEDADO A SIMILARIDADE DE FAIXADA, INSTALAÇOES DO BANCO
						2 DIAS PARA ACERTOS FINANCEIROS COM O BANCO
						VEDADO ADIANTAMENTO DE EMPRESTIMO PELO CORRESPONDENTE
						VEDADO A PRESTAÇAO DE GARANTIA
						PERMITIR AO BC ACESSO AO CONTRATO
						CONTRATANTE PODE PUNIR O CORRESPONDENTE /* É RESPONSAVEL !!! */
						CONTROLE DE QUALIDADE DO ATENDIMENTO
			
		CORRESPONDENTE PODE CONTRATAR OUTRO SUBCORRESPONDENTE UMA VEZ 
				!! NAO PODE CAMBIO !!
				/* EM UM UNICO NIVEL */
				
		CAMBIO : LIMITADA A 1000US COMPRA E VENDA EM ESPECIE !!
					 LIMITADA A 3000US CHEQUE, CHEQUE DE VIAGEM CARTAO PRE PAGO !
					 
								
								
	 BANCOS DIGITAIS /* NAO POSSUE NADA EM ATENDIMENTO FISICO 100% DIGITAL */
		/* SEM CORRESPONDENTES (AGENCIAS FISICAS) */
		
		ESTRUTURA ENXUTA /* ALOCAÇAO FISICA QUASE NULA + EFICIENTE */
		INTENSO USO DE TECNOLOGIA 
		MENOR CUSTO OPERACIONAL
		TARIFAS MAIS BAIXAS E SERVIÇOS GRATUITOS
		AGILIDADE, CONVENIENCIA E MENOR BUROCRACIA

NOVOS MODELOS DE NEGOCIOS 

	STARTUPS - EMPRESA JOVEM /* (NAO HA NUMERO DEFINIDO) */
			NEGOCIO INOVADOR /* AMBIENTE DE INCERTEZA */
			REPETIVEL /*  FACIL DE REPETIR O PROCESSO */ E ESCALAVEL /* PROCESSO FACIL SE AGIGANTAR */
			BASEADO EM UMA ESTRUTURA ENXUTA /* CUSTO DE OPERAÇAO BAIXO */
	
	FINTECHS - EMPRESA QUE ATUA NA INOVAÇAO DE SERVIÇO FINANCEIRO /* NAO NECESSARIAMENTE JOVEM */
			ESTRUTURA ENXUTA /* CUSTO DE OPERAÇAO BAIXO E MUITA TECNOLOGIA */
			NAO NECESSARIAMENTE É UM BANCO DIGITAL !!!!!!
		
	BIGTECHS - EMPRESAS DE TECNOLOGIA DOMINANTES NO MUNDO NOS ULTIMOSO ANOS
			FACEBOOK, GOOGLE, APPLE, AMAZON
			POR SER INOVAÇAO /* OFERTA SERVIÇOS FINANCEIROS SEM REGULAÇAO */
			
		RISCOS - EFICIENCIA /* NAO HA COMO SABER SE ESTA SENDO BEM ATENDIDO */
				 PRIVACIDADE /* ELES VENDEM DADOS PARA DIRECIONAMENTO DE VENDA */
				 CONCORRENCIA /* PODEM QUEBRAR CONCORRENCIA ENTRE EMPRESAS */
	
	PUBLICO DEFINE O MODELO
	
		B2C - BUSINESS TO CONSUMER /* MAIS COMUM, SERVE AO CLIENTE (MCDONALDS) */
		B2B - BUSINESS TO BUSINESS /* SERVE A OUTRA EMPRESA (FORNECEDOR, FABRICANTE) */
		B2B2C - BUSINESS TO BUSINESS TO CONSUMER /* PARCERIA, O CONSUMIDOR FINAL É ATENDIDO POR MEIO DE OUTRA EMPRESA, POR DEMANDA, NAO COMPRA O PRODUTO NA HORA */
		B2G - BUSINESS TO GOVERNMENT /* ATENDE O GOVERNO */
		B2E - BUSINESS TO EMPLOYEE /* ATENDE AO SEU PROPRIO FUNCIONARIO (EX:FUNCIONARIO PAGA MAIS BARATO) */
		C2C - CONSUMER TO CONSUMER /* INTERMEDIAÇAO ENTRE 2 CLIENTES (MARKETPLACE, SEP) */
		
	SEP - SOCIEDADE DE EMRPESTIMO ENTRE PESSOAS
		/* C2C - LIGA CONSUMIDORES */
		/* EMPRESA USA O DINHEIRO DE OUTROS CLIENTES PARA FORNECER EMPRESTIMOS */
		/* NAO ASSUME O RISCO DO NEGOCIO */
		
	SCD - SOCIEDADE DE CREDITO DIRETO
		/* USO DO CAPITAL DA PROPRIA EMPRESA PARA FORNECER EMPRESTIMOS */
		/* NECESSARIAMENTE PLATAFORMA ELETRONICA */
		
		AMBOS BAIXO RISCO SISTEMICO!!

OPEN BANKING /* PROCESSO DE COMPARTILHAMENTO PADRONIZADO DE DADOS POR INTEGRAÇAO DE SISTEMAS DOS BANCOS PARTICIPANTES */
	!! INICIATIVA DO BANCO CENTRAL DO BRASIL !!
	
	PRINCIPIO /* DADOS BANCARIOS PERTENCEM AO CLIENTE !!!!! */
		!! DEVE HAVER CONSENTIMENTO DO CLIENTE !!
		
	OBJETIVO /* + EFICIENCIA E CONCORRENCIA DO SFN (SISTEMA FINANCEIRO NACIONAL) */
		!! ABRE ESPAÇO PARA BANCOS MENORES !!
		
	PARTICIPANTES /* INSTITUIÇOES FINANCEIRAS, ~~ PAGAMENTO E OUTRAS AUTORIZADAS PELO BC */
		!! GRANDES BANCOS SAO OBRIGADOS , AS MENORES SAO FACULTATIVAS AINDA !!

	4 FASES DE IMPLEMENTAÇAO
		
		1 - PADRONIZAR DADOS DA INSTITUIÇAO /* CANAIS DE ATENDIMENTO, PRODUTOS/SERVIÇOS */
		2 - COMPARTILHAMENTO DOS DADOS DOS CLIENTES /* CADASTRAIS, TRANSACIONAIS DOS PRODUTOS/SERVIÇOS */
		3 - INICIO DE SERVIÇOS /* TRANSAÇAO DE PAGAMENTO e PROPOSTA DE OPERAÇAO DE CREDITO */
		4 - OUTROS SERVIÇOS MAIS COMPLEXOS

FUNÇOES E MOEDAS DIGITAIS 
	MOEDA - /* ATIVO QUE PODE SER UTILIZADO DE FORMA IMEDIATA PARA REALIZAR TRANSAÇOES */
		
		FUNÇOES
			- RESERVA DE VALOR /* TRANS PODER DE COMPRA DE HOJE PARA AMANHA (NAO NECESSARIO GASTAR AGORA) */
			- UNIDADE DE CONTA /* QUANTO CUSTA ? / PADRONIZA CUSTO (VALOR) */
			- MEIO DE TROCA /* INTERMEDIA UMA TROCA, BARBEIRO NAO PRECISA DE ALGUEM QUERENDO CORTAR O CABELO PAGANDO COMIDA */
	
		ATRIBUTOS
			- BAIXO CUSTO DE ESTOCAGEM /* FACIL DE ARMAZENAR/ACUMULAR */
			- BAIXO CUSTO DE TRANSAÇAO /* SABER USAR/FACIL USO */
			- DIFICIL DE FALSIFICAR
			- ALTA DURABILIDADE
			- DIVISIBILIDADE / HOMOGENEO
			
		MOEDA-MERCADORIA /* VALOR DE USO/INTRINSECO */
			/* DA PARA USAR A MOEDA PROPRIAMENTE DITA AO INVES DE USO PRA TROCA */

		MOEDA PADRAO-OURO /* CERTIFICADO DE OURO */
			/* PAPEL DIZENDO QUANTO OURO VOCE VALE */
			/* LASTREADA - QUANTIDADE FIXA DE OURO */
			
		FIDUCIARIO /* CONFIANÇA - TODOS ACREDITAM NO VALOR DELA (ATUAL) */
			/* FORÇA TODO O SISTEMA A USAR */
		
		ESCRITURAL /* SALDO DOS DEPOSITOS A VISTA (NA CONTA ELETRONICA) */
			/* HÁ VERSAO FISICA DELA (FIDUCIARIA) */
		
		MOEDA DIGITAL /* NAO HA VERSAO FISICA */
			
			VANTAGENS
				- MENOR CUSTO DE ARMAZENAGEM E TRANSAÇAO
				- MENOR RISCO DE ROUBOS, FURTOS E EXTRAVIOS
				- AUSENCIA DE RISO DE CONTAMINAÇAO /* FISICA MESMO */
				- MAIOR EFICIENCIA DAS POLITICAS ECONOMICAS (DINHEIRO PROGRAMAVEL)
					-POLITICA MONETARIA
					-POLITICA DE RENDAS
			
			DESAFIOS
				- PRIVACIDADE /* FICA REGISTRADO */
				- SENHORIAGEM /* FAZER MAIS DINHEIRO = INFLAÇAO */
				- SEGURANÇA
			
			CRIPTOMOEDAS, BITCOIN e BLOCKCHAIN
				- MOEDAS QUE USAM DA CRIPTOGRAFIA NOS REGISTROS (SO DA PRA VER COM CHAVE)
				
				BLOCKCHAIN /* REDE DE MILHARES DE COMPUTADORES DE USUARIOS, ESPALHADOS NO MUNDO */
					/* DECENTRALIZADO */
		
SHADOW BANKING /* SISTEMAS DE BANCO SOMBRA - INTERMEDIAÇAO DE CREDITO QUE TA FORA DO SISTEMA BANCARIO TRADICIONAL (NAO REGULADO) */
	!! FORA DA REGULAÇAO , FORA DO BALANÇO DO BANCO !!
	/* COMPRARAM-SE AS HIPOTECAS DOS BANCOS DANDO LIQUIDEZ AO MESMO */
		OBS: COMPRAVAM O DIREITO DE RECEBER A DIVIDA E DA EXECUÇAO (PEGAR IMOVEL)
	/* SEGMENTA, SEPARA OS BONS CLIENTES DOS RUINS (SUBPRIMES) */
	/* VENDE PARA INVESTIDORES OS CDO'S (PARTE DAS DIVIDAS) */
	/* RENDIA BASTANTE MAS TUDO BASEADO NOS SUBPRIMES, PAROU DE PAGAR ACABA TUDO */
		PROBELA: BANCO ENTROU NO NEGOCIO
		
	!! NAO E CRIME !!
	
	MAIOR PARTE É FUNDO DE INVESTIMENTO
	
	CRISE DE 2008 /* CRISE DOS SUBPRIMES */	
	
	HIPOTECA /* CREDITO BASEADO EM IMOVEL = FINANCIAMENTO */
			BAIXA LIQUIDEZ
			BAIXO RISCO DE INADIMPLENCIA /* NAO PAGOU TOMOU */
	
	
PIX / SISTEMAS DE PAGAMENTO

	BANCO CENTRAL - REGULADOR/GESTOR
		REGULADOR - CUIDA DAS REGRAS E APLICA PENALIDADES (BANCOS GRANDES FORÇADOS A PARTICIPAR DO PIX) 
			- EFETUA TESTES PREVIOS PARA INGRESSO
			- ANS - ACORDO DE NIVEL DE SERVIÇO - EXIGE 99% EM 2s (POR EXEMPLO)
		GESTOR - SPI (SISTEMA QUE FAZ AS LIQUIDAÇOES DOS PIX)
			   - DICT ( DIRETORIO DE CHAVES/ENDEREÇOS)
			
		LDL /* LIQUIDAÇAO DIFERIDA LIQUIDA */
			SISTEMA JUNTA MONTANTE DE DIVIDA ENTRE OS 2 BANCOS E MANDA APENAS A DIFERENÇA (+ TEMPO)
		
	SPB /* SISTEMA DE PAGAMENTOS BRASILEIROS */
		/* CONJ DE SISTEMAS E ENTIDADES QUE ATUAM PARA REALIZAR TRANSF DE RECURSOS DO SFN */
		NUCLEO SPB - STR 
		
		NAO INTEGRA O SPB /* LOGO NAO REGULADOS PELO BC - SEM ARRANJO */
			- VOLUME DE MOVIMENTAÇAO INFERIOR A 20BI
			- NUMERO DE TRANSAÇOES INFERIOR A 100MI
			- CARTAO DE LOJA
			- VALES ( DESTINADOS A FUNCIONARIOS )
			
		PIX /* PAGAMENTO INSTANTANEO BRASILEIRO */
			/* MEIO DE PAGAMENTO INSTANTANEO */
			/* ECOSSISTEMAS DE PAGAMENTOS INSTANTANEOS */
			CARACTERISTICAS
				- RAPIDO (40s)
				- DISPONIVEL (24h)
				- BARATO (0 TAXA P/ PESSOA FISICA , BARATO PARA OS DEMAIS CASOS)
				- VERSATIL ( PAGAR CONTA, IMPOSTO, COMPRAS )
			
			FORMAS DE INICIAR UM PIX
			
				CHAVE (ALEATORIA (PADRAO DO BANCO), CPF, CNPJ, EMAIL, TELEFONE)
					DICT (REPOSITORIO DAS CHAVES PIX DO USUARIO)
				
				QR CODE /* CHAVES ESTAO CODIFICADAS NELE */
					ESTATICO (VALOR PRE FIXADO/ OU TRANSFERIDOR DEFINE)
					DINAMICO (GERADO SOMENTE PARA UMA TRANSAÇAO ESPECIFICA)
				
				RECEBEDOR/PAGADOR NAO PRECISA TER CHAVE PIX (INFORMANDO APENAS AGENCIA CONTA E CPF)
			
			AGENDA EVOLUTIVA
				- PIX APROXIMAÇAO - NFC
				- PIX GARANTIDO - PARCELADO
				- PIX OFFLINE
				- PIX SAQUE/TROCO
				- MECANISMO DE DEVOLUÇAO
				- PIX COBRANÇA (COM VENCIMENTO)
				- DEBITO AUTOMATICO PIX
				
			SPI /* SISTEMA DE PAGAMENTOS INSTANTANEOS */
				/* SISTEMA DE LIQUIDAÇAO DE OBRIGAÇOES */
				- É O SISTEMA PROPRIAMENTE DITO, REALIZA AS TRASNFERENCIAS
		
PAGAMENTOS 
	ARRANJO DE PAGAMENTO /* CONJ DE REGRAS E DISCIPLINA PARA CADA TIPO DE PAGAMENTO (CARTAO, CHEQUE, PIX)*/
		!! ACEITO POR MAIS DE UM RECEBEDOR !!
	
		PARTICIPANTES
			- USUARIO /*  UTILIZA PARA PAGAR OU RECEBER */
			- INSTITUIDOR DE ARRANJO /* PESSOA JURIDICA RESPONSAVEL PELO ARRANJO */
			- INSTITUIÇAO DE PAGAMENTO (IP) /* PESSOA JURIDICA QUE ADERE A UM OU MAIS ARRANJO SENDO PRESTADOR DE SERVIÇO DE PAGAMENTO */
		
		SERVIÇO DE PAGAMENTOS
			- APORTES OU SAQUES /* COLOCAR SALDO OU TIRAR */
			- INSTRUÇOES DE PAGAMENTO /* ATO DE PAGAR OU DEPOSITAR */
			- GESTAO DE CONTAS DE PAGAMENTO
			- EMISSAO DE INSTRUMENTO DE PAGAMENTO /* CARTAO */
			- ACEITAÇAO DO INSTRUMENTO /* APROVAR */
		
		TIPOS DE IP
			- EMISSOR DE MOEDA ELETRONICA /* CONTA DE PAGEMAMENTO PRE-PAGO (VR, CARTAO PRE PAGO) */
			- EMISSOR DE INSTRUMENTO POS PAGO /* CARTAO DE CREDITO */
			- CREDENCIADOR /* CAPACITA ESTABELECIMENTOS A RECEBER PAGAMENTO DE INSTRUMENTOS */
			 !! NAO FAZ EMPRESTIMO NEM FINANCIAMENTO !!

MARKETPLACE /* LOCAL QUE PROMOVE O ENCONTRO ENTRE VENDEDOR/PROVEDOR DE SERVIÇO E COMPRADOR */
		MARKETPLACE FINANCEIRO /* SEP - CEDE CREDITO (QUEM TEM > ENDIVIDADO) */
				/* OPEN BANKING - VARIOS BANCOS ORFERTANDO O SERVIÇO AO CLIENTE - PADRONIZADO */
		
			MARKETPLACE COMO FACILITADOR DE PAGAMENTO - NAO E MARKETPLACE FINANCEIRO !!!
				/* NA PLATAFORMA TEM O INTERMEDIO (VENDEDOR - CIELO) PARA POSSIBILITAR O RECEBIMENTO DE PAGAMENTO POR CREDITO */
					!! LIQUIDAÇAO DE CREDITO E DEBITO OCORRE CENTRALIZADO NO BC
					SENDO ASSIM ENTRA COMO ARRANJO DE PAGAMENTO



				