ESTRUTURA DO SFN (SISTEMA FINANCEIRO NACIONAL)

REGLULADO POR
    - CONSTITUIÇAO FEDERAL #DELEGOU-SE AS LEIS COMPLEMENTARES A REGULAÇAO CAP 4 ART 192
    
    - LEIS COMPLEMENTARES #DELEGADO PELA CF PARA REGULAÇAO
        #MAIS DIFICIL DE SER APROVADA, MAIORIA ABSOLUTA = METADE + 1 DE TODOS
    
    - NORMA INFRALEGAIS # NAO E LEI

PARTES DO SFN
        
    NIVEL DE PAPEL
        
        NORMARTIZADORES (ENTIDADES) #PRECISA DE AUTORIZAÇAO PRA CAMBIO NO BR
            # ESTABELECEM REGRAS GERAIS
            RAMOS - ORGAOS NORMATIVOS
                - CMN(CONSELHO MONETARIO NACIONAL) #FINANCEIRO !!ORGAO SUPERIOR DO SFN!!
                    !! PODE ATUAR NOS OUTROS ESCOPOS
                    !! NORMAS DO CNM = !!!RESOLUÇAO!!! #BCB A PARTIR DE 2021 TAMBEM TEM RESOLUÇOES MAS DEIXA CLARO
                    !! BCB SECRETARIA, PUBLICA AS NORMAS/RESOLUÇOES DO CNM!!
                    COMPOSTO
                        -MINISTRO DA FAZENDA (PRESIDENTE) !!MEMBRO!!
                        -PRESIDENTE DO BC
                        -MINISTRO DO PLANEJAMENTO E ORÇAMENTO
                    
                    ATRIBUIÇOES
                        -COORDENA DIVIDA PUBLICA FEDERAL EXTERNA E INTERNA
                        -INSTANCIA MAXIMA DECISORIA DO SFN !!CASOS GERAIS E NAO CASOS/RECURSOS ESPECIFICOS
                            #PODE AGIR NOS OUTROS MERCADOS POIS PODEM INTERFERIR DEPENDENDO DO IMPACTO NO SEU PROPRIO MERCADO
                        -ELABORA/FORMULA POLITICAS MONETARIAS E DE CREDITO
                            COMOC(COMISSAO TECNICA DE MOEDA E DO CREDITO)
                                #ORGAO DE ASSESSORAMENTO TECNICO NA FORMULAÇAO DA POLITICA DA MOEDA E DO CREDITO
                                !!FORMADO POR #MEMBROS DO MINISTERIO DA FAZENDA, BCB, CVM E TESOURO NACIONAL
                        
                - CNSP(CONSELHO NACIONAL DE SEGUROS PRIVADOS) #SEGUROS
                    #NAO ABARCA SEGUROS PUBLICOS(DPVAT, SEGURO DESEMPREGO)
                    FUNÇOES
                        -REGULA E FISCALIZA SUBORDINADOS AO SNSP(SISTEMA DO CNSP) E PUNE
                        -FIXAR CARACTERISTICA GERAIS DOS 
                            CONTRATOS DE SEGURO, PREVIDENCIA PRIVADA ABERTA!!, CAPITALIZAÇAO(telecena) E RESSEGURO
                        -ESTABELECE AS DIRETRIZES GERAIS DAS OPERAÇOES DE RESSEGURO
                        -PRESCREVE CRITERIOS DE CONSTITUIÇAO DAS 
                            SOCIEDADES SEGURADORAS, de CAPITALIZAÇAO, ENTIDADES DE PREVIDENCIA ABERTA E RESSEGURADORES
                                #COM FIXAÇAO DOS LIMITES LEGAIS E TECNICOS DAS RESPECTIVAS OPERAÇOES
                                #DISCIPLINA TAMBEM A CORRETAGEM DE SEGURO E A PROFISSAO DE CORRETOR
                            
                - CNPC(CONSELHO NACIONAL DE PREVIDENCIA COMPLEMENTAR) #PREVIDENCIA
                    #REGULA PREVIDENCIA COMPLEMENTAR FECHADO!!!!!
                        #fechado = FUNCIONARIOS DE ALGUMA EMRPESA
                
                
        SUPERVISORES #PRA TER AUTORIZAÇAO PRECISA SEGUIR UM CONJUNTO DE REGRAS, COMO FARA
            # DETALHAM AS REGRAS, ASSEGURAM SEU CUMPRIMENTO, FISCALIZAM
            # TAMBEM SANCIONA QUANDO NECESSARIO
            # TAMBEM NORMATIZA A FIM DE ASSEGURAR O CUMPRIMENTO
            RAMOS / ORGAOS SUPERVISORES
                -BCB(BANCO CENTRAL DO BRASIL)#CMN
                    #MONETARIO, CREDITO E CAMBIO
                    -MISSAO !!GARANTIR ESTABILIDADE DO PODER DE COMPRA DA MOEDA(INFLAÇAO)
                            !!ZELAR POR SISTEMA FINANCEIRO SOLIDO, EFICIENTE E COMPETITIVO
                            !!FOMENTAR BEM ESTAR ECONOMICO DA SOCIEDADE
                            
                    -OBJETIVOS !!ZELAR PELA ESTABILIDADE E PELA EFICIENCIA DO SISTEMA FINANCEIRO 
                               !!SUAVIZAR FLUTUAÇOES DO NIVEL DA ATIVIDADE ECONOMICA
                               !!FOMENTAR AMPLO EMPREGO 
                    
                    FUNÇOES/PAPEIS !!!!!!!!!
                        -SUPERVISOR DOS MERCADOS DE CREDITO, CAMBIO E MOEDA
                        -AUTARQUIA FEDERAL SEM VINCULO COM MINISTERIO/SEM VINCULO HIERARQUICO/NAO MANDA
                        -DETEM O MONOPOLIO DE EMITIR PAPEL MOEDA
                        -DITRIBUIÇAO E LOGISTICA DESSSE NUMERARIO
                        -BANCO DOS BANCOS #ONDE OS BANCOS POSSUEM CONTA/TRANSFERENCIA ENTRE BANCOS/EMPRESTIMO
                        -BANQUEIRO DO GOVERNO #CONTAUNICA DO TESOURO NACIONAL!!!! / ATIVOS DE RESERVA: OURO, MOEDA ESTRANGEIRA E OUTROS
                        -EXECUTOR DA POLITICA MONETARIA #DETERMINA QUANTIDADE DE MOEDA CIRCULANDO DE ACORDO COM DETERMINAÇOES DO CNM
                            # NAO PRECISA DA AUTORIZAÇAO DO CNM PARA EMITIR MOEDA
                            !!MEIO CIRCULANTE!!
                        -EXECUTOR DA POLITICA CAMBIAL #CONFORME O CNM DETERMINA
                            #CONTROLA OU NAO O VALOR DA MOEDA ESTRANGEIRA
                            !! CORRETORAS CAMBIAIS SO PODEM ATUAR NO MERCADO CAMBIAL!!
                            
                            COPOM - ORGAO DO BANCO CENTRAL FORMADO POR
                                -PRESIDENTE DO BC E DIRETORES
                                - DEFINE A CADA !!!45!!! DIAS TAXA BASICA DE JUROS DA ECONOMIA: SELIC!!!!
                        
                -CVM(COMISSAO DE VALOREES IMOBILIARIOS)#CNM
                    #CAPITAL
                    #FISCALIZA, NORMATIZA, DISCIPLINA E DESENVOLVO O MERCADO DE VALORES IMOBILIARIOS
                    AUTARQUIA EM REGIME ESPECIAL
                    VINCULADA ADMINISTRATIVAMENTE AO MINISTERIO DA FAZENDA !!
                    PERSONALIDADE JURIDICA E PATRIMONIOS PROPRIOS #CNPJ PROPRIO = AUTARQUIA
                    NAO RECEBE ORDEM/SEM SUBORNINAÇAO HIERARQUICA
                    MANDATO FIXO E ESTABILIDADE DE DIRIGENTES
                    AUTONOMIA FINANCEIRA E ORÇAMENTARIA
                    
                    OBS !!CORRETORA E DISTRUIDORA DE TITULOS E DE VALORES MOBILIARIOS SAO IGUAIS!!
                    
                    OBJETIVOS
                        -DESENVOLVER O MERCADO DE CAPITAIS
                        -EFICIENCIA E FUNCIONAMENTO DO MERCADO
                        -PROTEÇAO DOS INVESTIDORES
                        -ACESSO A INFORMAÇAO ADEQUADA
                        -FISCALIZAÇAO E PUNIÇAO
                    
                -SUSEP(SUPERINTENDENCIA DE SEGUROS PRIVADOS)#CNSP
                    #MERCADO DE SEGUROS PRIVADOS
                    #CONTROLE E FISCALIZAÇAO DE SEGURO, PREVIDENCIA PRIVADA ABERTA, CAPITALIZAÇAO E RESSEGURO
                    #FAZ SECRETARIA PARA O CNSP, CUMPRE E FAZ CUMPRIR DETERMIAÇOES DO CNSP
             
                -PREVIC(SUPERINTENDENCIA NACIONAL DE PREVIDENCIA COMPLEMENTAR)#CNPC
                    #MERCADO PREVIDENCIA !!!!FECHADA!!!!!!!!!!
                    AUTARQUIA ESPECIAL !VINCULADA ADMINISTRATIVAMENTE AO MINISTERIO DO TRABALHO E PREVIDENCIA
                    PERSONALIDADE JURIDICA E PATRIMONIOS PROPRIOS #CNPJ PROPRIO = AUTARQUIA
                    NAO RECEBE ORDEM/SEM SUBORNINAÇAO HIERARQUICA
                    REGULA PREVIDENCIA !!FECHADA!! COMPLEMENTAR(FUNDO DE PENSAO)
                    
        CRSFN(CONSELHO DE RECURSOS DO SFN)
            -ORGAO COLEGIADO JULGA RECURSOS EM ULTIMA INSTANCIA SANÇOES APLICADAS POR
                BCB e CVM #MERCADO FINANCEIRO
            E NOS PROCESSOS DE LAVAGEM DE DINHEIRO SANCIONADO PELO
                COAF, SUSEP E ETC
            COMPOSTO POR
                -2 MINISTERIO DA FAZENDA, 1 BC, 1 CVM, 4 MERCADOS FINANCEIROS E DE CAPITAIS
                
        OPERADORES #APLICAM, SEGUEM AS REGRAS, CONTATO COM O PUBLICO
            #BANCOS, POR EXEMPO
            
            INSTITUIÇOES FINANCEIRAS
                INSTITUIÇOES MONETARIAS(BANCARIAS) #CAPTAM DEPOSITOS A VISTA
                    
                    BANCOS COMERCIAIS #BANCO DO BRASIL
                        #INSTITUIÇOES FINANCEIRAS QUE ATUAM NA INTERMEDIAÇAO FINANCEIRA CAPTANDO(PEGA DINHEIRO EMPRESTADO) RECURSOS DOS AGENTE ECONOMICOS SUPERAVITARIOS E EMPRESTA(APLICA) PARA AGENTES DEFICITARIOS
                        !! CAPTAM DEPOSITO A VISTA (OFERECEM CONTA CORRENTE) - (MULTIPLICAÇAO MONETARIA) OS 2 USAM O DINHEIRO AO MESMO TEMPO
                    
                    CAIXAS ECONOMICAS #CAIXA ECONOMICA FEDERAL
                        #EMPRESA PUBLICA QUE EXERCE ATIVIDADE TIPICA DO BANCO COMERCIAL
                         !!OBS BANCO COM PEGADA MAIS !!SOCIAL!! - PRIORIDADE INSTITUCIONAL PARA CONCESSAO DE EMPRESTIMOS E FINANCIAMENTOS DE PROGRAMAS E PROJETOS DE NATUREZA SOCIAL
                
                    COOPERATIVA DE CREDITO #INSTITUIÇAO MONETARIA POREM NAO É BANCO
                        !!CAPTAM DEPOSITOS A VISTA TAMBEM POREM - DOS CLIENTE/DONOS (COOPERADOS) - !!
                        !!OBJETIVO NAO E LUCRO - AS VEZES !!SOBRA!! E É DISTRUIDO ENTRE COOPERADOS !!
                        !!TAMBEM MULTIPLICA MOEDA!!
                        !!DEVE SE ASSOCIAR A COOPERATIVA!!
                     
            
                BANCOS MULTIPLOS #DEVE TER NO MINIMO 2 CARTEIRAS E OBRITAGORIAMENTE !!COMERCIAL!! OU !!INVESTIMENTO!!
                    !! E SER ORGANIZADO SOB FORMA DE SOCIEDADE ANONIMA !!
                        
                INSTITUIÇOES FINANCEIRAS NAO BANCARIAS
                    
                    CORRETORAS E DISTRIBUIDORAS DE TITULOS E VALORES IMOBILIARIOS #CTVM e DTVM
                    
                    SOCIEDADES DE CREDITO, FINANCIAMENTO E INVESTIMENTOS #FINANCEIRAS
                    
                    ASSOCIAÇOES DE POUPANÇA E EMPRESTIMO #SETOR IMOBILIARIO , POUPEX
                    
                    SOCIEDADE DE CREDITO IMOBILIARIO
                    
        INSTITUIÇAO NAO FINANCEIRA
            
            ADMINISTRADORA DE CONSORCIOS #NAO INTERMEDIA, AUTOFINANCIAMENTO
            
            INSTITUIÇAO DE PAGAMENTO #NUBANK #FORNECE EMPRESTIMO VIA SOCIEDADE DE CREDITO (NU PAGAMENTOS)
                !!NAO FAZ PARTE DO SFN!!
                    
        EX PRATICO # CNM(NORMATIZADOR) - BCB ATUARA PARA PROMOVER A SOLIDEZ, FUNCIONALIDADE E MELHORA DO SPB
                   # BCB(SUPERVISOR) - APLICA AS REGRAS, CRIA PIX PARA MELHORAR O SPB, COMO FARA ISSO
                   # BB (OPERADOR) - CUMPRE A REGRA, AGE JUNTO AO PUBLICO
                   
                   !!SUBSISTEMA NORMATIVO (SUPERVISORES E NORMATIZADORES)
                   !!SUBSISTEMA DE INTERMEDIAÇAO (OPERADORES)
                   
    RAMOS/MERCADOS
        
        FINANCEIRO, SEGUROS, PREVIDENCIA
        
        MERCADOS (FINANCEIRO)
            - MONETARIO #FORNECE PAPEL MOEDA E MOEDA ESCRITURAL
            - CREDITO #RECURSOS P/CONSUMO E FUNCIONAMENTO DE EMPRESAS (eMPRESTIMO, MAIS CURTO PRAZO)
            - CAPITAIS #PROJETO GRANDE, PESQUISA, CONSTRUIR FABRICA (LONGO PRAZO)
            - CAMBIO #COMPRA E VENDA DE MOEDA ESTRANGEIRA
     
    OBS !! EXECUTORES DE POLITICAS DE CREDITO BNDES, BB e CAIXA !!
        !! CHEQUE - COMPE - BB !!
        
        